---
linters:
    flake8:
    eslint:
        config: './eslint.config'
        ignore: 'quotes'
    csslint:
        ignore: 'order-alphabetical,box-sizing'
files:
    ignore:
        - 'node_modules/*'
        - 'src/generated/*'
        - 'src/index.js'
        - 'dist/bundle.js'
        - 'dist/bundle.js'
