---
linters:
    flake8:
    eslint:
        config: './eslint.config'

    csslint:
        ignore: 'order-alphabetical,box-sizing,fallback-colors,duplicate-properties,overqualified-elements,important'
files:
    ignore:
        - 'node_modules/*'
        - 'src/generated/*'
        - 'src/index.js'
        - 'dist/bundle.js'
        - 'dist/bundle.js'
